#!/bin/bash

#Check argument (how many numbers to generate)
if [ -z "$1" ]; then
	echo "Use: $0 [ n ]"
	exit 1
fi

N=$1

ARG=$(./nums_generator $N)

echo "--- Testing $N numbers ---"
echo -n "--- Movements: "
./push_swap "$ARG" | wc -l 
echo -n "--- Result: "
./push_swap "$ARG" | ./checker_linux $ARG
